import { saveShadowIntent, saveShadowSession } from "@binaryreplay/db";
import { bookImbalance, meanReversion, momentum, passiveMaker, probabilityThreshold, type Strategy, type StrategyIntent, type StrategySnapshot } from "@binaryreplay/strategies";
import { simulateIntent } from "@binaryreplay/simulator";
import { SOMNIA_TESTNET_ADDRESSES, SomniaMarkets } from "@somnia-chain/markets-sdk";
import { somniaShannon } from "@somnia-chain/markets-sdk/chains";

const json = (value: unknown) => JSON.parse(JSON.stringify(value, (_key, item) => typeof item === "bigint" ? item.toString() : item));
const dreamdex = () => new SomniaMarkets({ chain: somniaShannon, indexerUrl: process.env.DREAMDEX_INDEXER_URL ?? "https://dev.smk.somnia.host/v1/graphql", wsRpcUrl: process.env.SOMNIA_WS_RPC_URL ?? "wss://api.infra.testnet.somnia.network/ws", addresses: SOMNIA_TESTNET_ADDRESSES });
const references: Record<string, Strategy<any>> = { "probability-threshold": probabilityThreshold, "book-imbalance": bookImbalance, momentum, "mean-reversion": meanReversion, "passive-maker": passiveMaker };
export type ShadowConfig = { sessionId: string; marketId: `0x${string}`; poolAddress: `0x${string}`; strategyId: keyof typeof references; strategyVersion: string; strategyConfiguration: Record<string, bigint>; tickSize: bigint; lotSize: bigint; maxSlippageBps: bigint; latencyMs: bigint };
export type ShadowSink = { session: (value: { id: string; marketId: string; strategyDefinitionId: string; status: string; config: unknown; endedAt?: Date }) => Promise<void>; intent: (value: { id: string; shadowSessionId: string; marketId: string; sequence: bigint; observedAt: bigint; side: string; quantity: bigint; referencePrice?: bigint; decision: unknown }) => Promise<void> };
export const postgresShadowSink: ShadowSink = { session: saveShadowSession, intent: saveShadowIntent };

/** Read-only live shadow observer. It has no signer, wallet, or SDK write call. */
export class LiveShadowWorker {
  private readonly exchange = dreamdex(); private unsubscribe?: () => void; private stopWatch?: () => void; private sequence = 0n; private activeMarketId: `0x${string}`;
  constructor(private readonly config: ShadowConfig, private readonly sink: ShadowSink = postgresShadowSink) { this.activeMarketId = config.marketId; }
  async start() { await this.sink.session({ id: this.config.sessionId, marketId: this.activeMarketId, strategyDefinitionId: `${this.config.strategyId}@${this.config.strategyVersion}`, status: "SIMULATED_NOT_ON_CHAIN", config: json(this.config) }); const watched = await this.exchange.client.watchMarket(this.config.poolAddress); this.stopWatch = () => watched.stop(); this.unsubscribe = this.exchange.client.subscribeLive(() => void this.observe()); await this.observe(); }
  async stop() { this.unsubscribe?.(); this.stopWatch?.(); this.exchange.close(); }
  private async rollover(successor: `0x${string}`) { await this.sink.session({ id: this.config.sessionId, marketId: this.activeMarketId, strategyDefinitionId: `${this.config.strategyId}@${this.config.strategyVersion}`, status: "ROLLED_OVER", config: { successorMarketId: successor }, endedAt: new Date() }); this.activeMarketId = successor; this.sequence = 0n; await this.sink.session({ id: `${this.config.sessionId}:${successor.slice(2, 12)}`, marketId: successor, strategyDefinitionId: `${this.config.strategyId}@${this.config.strategyVersion}`, status: "SIMULATED_NOT_ON_CHAIN", config: json(this.config) }); }
  private async observe() { const client = this.exchange.client; const market = client.getLiveMarketByPool(this.config.poolAddress); if (!market || market.marketType !== "BINARY" || market.status !== "Trading") return; const observedMarketId = market.marketId as `0x${string}`; if (observedMarketId.toLowerCase() !== this.activeMarketId.toLowerCase()) await this.rollover(observedMarketId);
    const rawBook: any = client.getLiveBinaryOrderBookByMarket(this.activeMarketId, { depth: 50 }); const yesBids = rawBook.yesBids ?? []; const yesAsks = rawBook.yesAsks ?? []; const noBids = rawBook.noBids ?? []; const noAsks = rawBook.noAsks ?? []; const now = BigInt(Math.floor(Date.now() / 1000)); const snapshot: StrategySnapshot = { marketId: this.activeMarketId, virtualTime: now, marketStatus: "Trading", yesBids, yesAsks, noBids, noAsks, lastTradePrice: undefined, referencePrice: undefined };
    const intents = references[this.config.strategyId].evaluate(snapshot, { upQuantity: 0n, downQuantity: 0n, collateral: 0n }, this.config.strategyConfiguration);
    for (const intent of intents) await this.persistIntent(intent, snapshot, rawBook, now, BigInt(market.expiry));
  }
  private async persistIntent(intent: StrategyIntent, snapshot: StrategySnapshot, rawBook: unknown, observedAt: bigint, expiry: bigint) { const execution = simulateIntent(intent, { marketId: this.activeMarketId, virtualTime: observedAt, expiry, marketStatus: "Trading", tickSize: this.config.tickSize, lotSize: this.config.lotSize, maxSlippageBps: this.config.maxSlippageBps, latencyMs: this.config.latencyMs, book: { yesBids: snapshot.yesBids, yesAsks: snapshot.yesAsks, noBids: snapshot.noBids, noAsks: snapshot.noAsks } }); const sessionId = this.activeMarketId === this.config.marketId ? this.config.sessionId : `${this.config.sessionId}:${this.activeMarketId.slice(2, 12)}`; const sequence = ++this.sequence; await this.sink.intent({ id: `${sessionId}:${sequence}`, shadowSessionId: sessionId, marketId: this.activeMarketId, sequence, observedAt, side: intent.action, quantity: intent.quantity ?? 0n, referencePrice: intent.limitPrice, decision: json({ label: "SIMULATED — NOT ON-CHAIN", intent, bestBid: snapshot.yesBids[0] ?? null, bestAsk: snapshot.yesAsks[0] ?? null, visibleLiquidity: rawBook, expectedExecution: execution }) }); }
}
