import { boolean, index, jsonb, numeric, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

// All chain quantities/timestamps use numeric(78,0): exact uint256-safe integers, represented as strings in TypeScript.
const raw = (name: string) => numeric(name, { precision: 78, scale: 0 });
const captured = () => timestamp("captured_at", { withTimezone: true }).notNull();

export const marketWindows = pgTable("market_windows", { id: text("id").primaryKey(), marketId: text("market_id").notNull(), poolAddress: text("pool_address").notNull(), poolNonce: raw("pool_nonce"), marketAddress: text("market_address"), asset: text("asset").notNull(), intervalSec: raw("interval_sec"), tradingStart: raw("trading_start").notNull(), expiry: raw("expiry").notNull(), status: text("status").notNull(), resolution: jsonb("resolution"), createdAt: timestamp("created_at", { withTimezone: true }).notNull() }, (table) => [uniqueIndex("market_windows_market_id_uq").on(table.marketId), index("market_windows_pool_nonce_idx").on(table.poolAddress, table.poolNonce), index("market_windows_expiry_idx").on(table.expiry)]);
export const captureSessions = pgTable("capture_sessions", { id: text("id").primaryKey(), marketId: text("market_id").notNull(), mode: text("mode").notNull(), startedAt: captured(), endedAt: timestamp("ended_at", { withTimezone: true }), sdkVersion: text("sdk_version").notNull(), status: text("status").notNull(), lastEventAt: timestamp("last_event_at", { withTimezone: true }), lastBlock: raw("last_block"), metadata: jsonb("metadata").notNull() }, (table) => [index("capture_sessions_market_started_idx").on(table.marketId, table.startedAt)]);
export const captureGaps = pgTable("capture_gaps", { id: text("id").primaryKey(), captureSessionId: text("capture_session_id").notNull(), marketId: text("market_id").notNull(), reason: text("reason").notNull(), fromBlock: raw("from_block"), toBlock: raw("to_block"), detectedAt: captured(), recoveredAt: timestamp("recovered_at", { withTimezone: true }), details: jsonb("details").notNull() }, (table) => [index("capture_gaps_session_detected_idx").on(table.captureSessionId, table.detectedAt), index("capture_gaps_market_idx").on(table.marketId)]);
export const sourceOrders = pgTable("source_orders", { id: text("id").primaryKey(), marketId: text("market_id").notNull(), captureSessionId: text("capture_session_id"), sourceOrderId: text("source_order_id").notNull(), poolAddress: text("pool_address").notNull(), owner: text("owner"), side: text("side"), isBid: boolean("is_bid"), price: raw("price"), fullQuantity: raw("full_quantity"), remainingQuantity: raw("remaining_quantity"), filledQuantity: raw("filled_quantity"), status: text("status"), placedAt: raw("placed_at"), blockNumber: raw("block_number"), txHash: text("tx_hash"), source: jsonb("source").notNull() }, (table) => [uniqueIndex("source_orders_market_source_uq").on(table.marketId, table.sourceOrderId), index("source_orders_market_time_idx").on(table.marketId, table.placedAt)]);
export const sourceFills = pgTable("source_fills", { id: text("id").primaryKey(), marketId: text("market_id").notNull(), captureSessionId: text("capture_session_id"), sourceFillId: text("source_fill_id").notNull(), poolAddress: text("pool_address").notNull(), price: raw("price").notNull(), quantity: raw("quantity").notNull(), quoteQuantity: raw("quote_quantity").notNull(), timestamp: raw("timestamp").notNull(), blockNumber: raw("block_number").notNull(), logIndex: raw("log_index").notNull(), txHash: text("tx_hash").notNull(), source: jsonb("source").notNull() }, (table) => [uniqueIndex("source_fills_market_source_uq").on(table.marketId, table.sourceFillId), index("source_fills_market_time_idx").on(table.marketId, table.timestamp), index("source_fills_block_log_idx").on(table.blockNumber, table.logIndex)]);
export const sourceCandles = pgTable("source_candles", { id: text("id").primaryKey(), marketId: text("market_id").notNull(), poolAddress: text("pool_address").notNull(), intervalSec: raw("interval_sec").notNull(), bucketStart: raw("bucket_start").notNull(), openPrice: raw("open_price").notNull(), high: raw("high").notNull(), low: raw("low").notNull(), closePrice: raw("close_price").notNull(), baseVolume: raw("base_volume").notNull(), quoteVolume: raw("quote_volume").notNull(), tradeCount: raw("trade_count").notNull(), source: jsonb("source").notNull() }, (table) => [uniqueIndex("source_candles_market_bucket_uq").on(table.marketId, table.intervalSec, table.bucketStart), index("source_candles_market_time_idx").on(table.marketId, table.bucketStart)]);
export const replayDatasets = pgTable("replay_datasets", { id: text("id").primaryKey(), marketId: text("market_id").notNull(), capturedAt: captured(), integrityHash: text("integrity_hash").notNull(), source: jsonb("source").notNull(), derived: jsonb("derived").notNull() }, (table) => [uniqueIndex("replay_datasets_market_hash_uq").on(table.marketId, table.integrityHash), index("replay_datasets_market_captured_idx").on(table.marketId, table.capturedAt)]);
export const replayEvents = pgTable("replay_events", { id: text("id").primaryKey(), datasetId: text("dataset_id").notNull(), marketId: text("market_id").notNull(), sequence: raw("sequence").notNull(), eventTimestamp: raw("event_timestamp").notNull(), eventKind: text("event_kind").notNull(), sourceRecordId: text("source_record_id"), payload: jsonb("payload").notNull() }, (table) => [uniqueIndex("replay_events_dataset_sequence_uq").on(table.datasetId, table.sequence), index("replay_events_market_time_idx").on(table.marketId, table.eventTimestamp)]);
export const strategyDefinitions = pgTable("strategy_definitions", { id: text("id").primaryKey(), name: text("name").notNull(), version: text("version").notNull(), definitionHash: text("definition_hash").notNull(), language: text("language").notNull(), source: text("source").notNull(), parameters: jsonb("parameters").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull() }, (table) => [uniqueIndex("strategy_definitions_hash_uq").on(table.definitionHash), index("strategy_definitions_name_idx").on(table.name)]);
export const strategyRuns = pgTable("strategy_runs", { id: text("id").primaryKey(), datasetId: text("dataset_id").notNull(), datasetHash: text("dataset_hash").notNull(), marketId: text("market_id").notNull(), strategyDefinitionId: text("strategy_definition_id").notNull(), strategyId: text("strategy_id").notNull(), strategyVersion: text("strategy_version").notNull(), strategyHash: text("strategy_hash").notNull(), runHash: text("run_hash").notNull(), initialCapital: raw("initial_capital").notNull(), latencyMs: raw("latency_ms").notNull(), simulatorConfig: jsonb("simulator_config").notNull(), results: jsonb("results").notNull(), startedAt: captured(), completedAt: timestamp("completed_at", { withTimezone: true }), status: text("status").notNull(), config: jsonb("config").notNull(), deterministicSeed: text("deterministic_seed").notNull(), error: text("error") }, (table) => [uniqueIndex("strategy_runs_run_hash_uq").on(table.runHash), index("strategy_runs_dataset_hash_idx").on(table.datasetHash), index("strategy_runs_dataset_idx").on(table.datasetId), index("strategy_runs_market_started_idx").on(table.marketId, table.startedAt)]);
export const simulatedOrders = pgTable("simulated_orders", { id: text("id").primaryKey(), strategyRunId: text("strategy_run_id").notNull(), marketId: text("market_id").notNull(), clientOrderKey: text("client_order_key").notNull(), side: text("side").notNull(), requestedQuantity: raw("requested_quantity").notNull(), limitPrice: raw("limit_price"), submittedAt: raw("submitted_at").notNull(), latencyMs: raw("latency_ms").notNull(), status: text("status").notNull(), assumptions: jsonb("assumptions").notNull() }, (table) => [uniqueIndex("simulated_orders_run_client_key_uq").on(table.strategyRunId, table.clientOrderKey), index("simulated_orders_run_time_idx").on(table.strategyRunId, table.submittedAt)]);
export const simulatedFills = pgTable("simulated_fills", { id: text("id").primaryKey(), simulatedOrderId: text("simulated_order_id").notNull(), strategyRunId: text("strategy_run_id").notNull(), marketId: text("market_id").notNull(), price: raw("price").notNull(), quantity: raw("quantity").notNull(), fee: raw("fee").notNull(), filledAt: raw("filled_at").notNull(), sourceEventId: text("source_event_id") }, (table) => [index("simulated_fills_order_idx").on(table.simulatedOrderId), index("simulated_fills_run_time_idx").on(table.strategyRunId, table.filledAt)]);
export const runMetrics = pgTable("run_metrics", { id: text("id").primaryKey(), strategyRunId: text("strategy_run_id").notNull(), metricKey: text("metric_key").notNull(), metricValue: text("metric_value").notNull(), unit: text("unit"), metadata: jsonb("metadata").notNull() }, (table) => [uniqueIndex("run_metrics_run_key_uq").on(table.strategyRunId, table.metricKey)]);
export const shadowSessions = pgTable("shadow_sessions", { id: text("id").primaryKey(), marketId: text("market_id").notNull(), strategyDefinitionId: text("strategy_definition_id").notNull(), startedAt: captured(), endedAt: timestamp("ended_at", { withTimezone: true }), status: text("status").notNull(), captureSessionId: text("capture_session_id"), config: jsonb("config").notNull() }, (table) => [index("shadow_sessions_market_started_idx").on(table.marketId, table.startedAt)]);
export const shadowIntents = pgTable("shadow_intents", { id: text("id").primaryKey(), shadowSessionId: text("shadow_session_id").notNull(), marketId: text("market_id").notNull(), sequence: raw("sequence").notNull(), observedAt: raw("observed_at").notNull(), side: text("side").notNull(), quantity: raw("quantity").notNull(), referencePrice: raw("reference_price"), decision: jsonb("decision").notNull() }, (table) => [uniqueIndex("shadow_intents_session_sequence_uq").on(table.shadowSessionId, table.sequence), index("shadow_intents_market_time_idx").on(table.marketId, table.observedAt)]);
export const verificationRecords = pgTable("verification_records", { id: text("id").primaryKey(), marketId: text("market_id").notNull(), datasetId: text("dataset_id"), strategyRunId: text("strategy_run_id"), kind: text("kind").notNull(), verifiedAt: captured(), chainId: raw("chain_id"), blockNumber: raw("block_number"), txHash: text("tx_hash"), result: text("result").notNull(), evidence: jsonb("evidence").notNull() }, (table) => [index("verification_records_market_time_idx").on(table.marketId, table.verifiedAt), index("verification_records_run_idx").on(table.strategyRunId)]);
export const optionalRunAttestations = pgTable("optional_run_attestations", { id: text("id").primaryKey(), strategyRunId: text("strategy_run_id").notNull(), attester: text("attester").notNull(), attestedAt: captured(), signature: text("signature").notNull(), payloadHash: text("payload_hash").notNull(), metadata: jsonb("metadata").notNull() }, (table) => [uniqueIndex("optional_run_attestations_run_uq").on(table.strategyRunId), index("optional_run_attestations_attester_idx").on(table.attester)]);
export const liveCaptureRecords = pgTable("live_capture_records", { id: text("id").primaryKey(), marketId: text("market_id").notNull(), capturedAt: captured(), kind: text("kind").notNull(), blockNumber: raw("block_number"), payload: jsonb("payload").notNull() }, (table) => [index("live_capture_records_market_captured_idx").on(table.marketId, table.capturedAt)]);
