import { listShadowIntents, listShadowSessions } from "@binaryreplay/db";

export const dynamic = "force-dynamic";
export default async function ShadowPage() {
  try {
    const sessions = await listShadowSessions(); const current = sessions.at(-1); const intents = current ? await listShadowIntents(current.id) : [];
    return <main className="page"><p className="eyebrow">Live shadow mode</p><h1>SIMULATED — NOT ON-CHAIN</h1><p className="lead">Live DreamDEX observations feed a selected strategy. Intents and expected executions are research-only and never broadcast transactions.</p>{current ? <><section className="card"><small>ACTIVE / LATEST SHADOW SESSION</small><div className="metric"><span>marketId</span><span>{current.marketId}</span></div><div className="metric"><span>status</span><span>{current.status}</span></div><div className="metric"><span>started</span><span>{String(current.startedAt)}</span></div></section><section className="card"><small>LIVE SHADOW INTENTS · SIMULATED — NOT ON-CHAIN</small>{intents.slice(-30).reverse().map((intent) => { const decision: any = intent.decision; return <div className="metric" key={intent.id}><span>{intent.observedAt} · {intent.marketId} · {intent.side} {intent.quantity} @ {intent.referencePrice ?? "market"}</span><span>bid {decision?.bestBid?.price ?? "n/a"} · ask {decision?.bestAsk?.price ?? "n/a"} · {decision?.expectedExecution?.status ?? "NOT_FILLED"}</span></div>})}{!intents.length && <p className="muted">Awaiting a genuine Trading market update.</p>}</section></> : <section className="empty"><strong>No shadow session is running.</strong><p>Start the optional read-only shadow worker with a verified Trading marketId and matching pool address.</p></section>}</main>;
  } catch { return <main className="page"><p className="eyebrow">Live shadow mode</p><h1>SIMULATED — NOT ON-CHAIN</h1><section className="empty"><strong>Shadow storage is unavailable.</strong><p>Configure PostgreSQL and apply migrations before inspecting shadow sessions.</p></section></main>; }
}
