ALTER TABLE strategy_runs ADD COLUMN IF NOT EXISTS dataset_hash text;
ALTER TABLE strategy_runs ADD COLUMN IF NOT EXISTS strategy_id text;
ALTER TABLE strategy_runs ADD COLUMN IF NOT EXISTS strategy_version text;
ALTER TABLE strategy_runs ADD COLUMN IF NOT EXISTS strategy_hash text;
ALTER TABLE strategy_runs ADD COLUMN IF NOT EXISTS run_hash text;
ALTER TABLE strategy_runs ADD COLUMN IF NOT EXISTS initial_capital numeric(78,0);
ALTER TABLE strategy_runs ADD COLUMN IF NOT EXISTS latency_ms numeric(78,0);
ALTER TABLE strategy_runs ADD COLUMN IF NOT EXISTS simulator_config jsonb;
ALTER TABLE strategy_runs ADD COLUMN IF NOT EXISTS results jsonb;
UPDATE strategy_runs SET dataset_hash = COALESCE(dataset_hash, ''), strategy_id = COALESCE(strategy_id, strategy_definition_id), strategy_version = COALESCE(strategy_version, 'unknown'), strategy_hash = COALESCE(strategy_hash, ''), run_hash = COALESCE(run_hash, id), initial_capital = COALESCE(initial_capital, 0), latency_ms = COALESCE(latency_ms, 0), simulator_config = COALESCE(simulator_config, '{}'::jsonb), results = COALESCE(results, '{}'::jsonb);
ALTER TABLE strategy_runs ALTER COLUMN dataset_hash SET NOT NULL;
ALTER TABLE strategy_runs ALTER COLUMN strategy_id SET NOT NULL;
ALTER TABLE strategy_runs ALTER COLUMN strategy_version SET NOT NULL;
ALTER TABLE strategy_runs ALTER COLUMN strategy_hash SET NOT NULL;
ALTER TABLE strategy_runs ALTER COLUMN run_hash SET NOT NULL;
ALTER TABLE strategy_runs ALTER COLUMN initial_capital SET NOT NULL;
ALTER TABLE strategy_runs ALTER COLUMN latency_ms SET NOT NULL;
ALTER TABLE strategy_runs ALTER COLUMN simulator_config SET NOT NULL;
ALTER TABLE strategy_runs ALTER COLUMN results SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS strategy_runs_run_hash_uq ON strategy_runs(run_hash);
CREATE INDEX IF NOT EXISTS strategy_runs_dataset_hash_idx ON strategy_runs(dataset_hash);
